create or replace database DBT_DEV;
create or replace database DBT_SIT;
create or replace database ENTAINDEV;
create or replace database METADATACONTROLDB;
create or replace database PC_DBT_DB COMMENT='System created db for partner elt integration.';
create or replace database TEST;
create or replace schema DBT_DEV.DBO;
create or replace schema DBT_DEV.INTEGRATION;
create or replace schema DBT_DEV.INTEGRATION_MARTS;
create or replace schema DBT_DEV.META;
create or replace schema DBT_DEV.PUBLIC;
create or replace schema DBT_DEV.STG;
create or replace schema DBT_SIT.INTEGRATION;
create or replace schema DBT_SIT.META;
create or replace schema DBT_SIT.PUBLIC;
create or replace schema DBT_SIT.STG;
create or replace schema ENTAINDEV.DBT_SCH;
create or replace schema ENTAINDEV.PROCESSING_SCH;
create or replace schema ENTAINDEV.PUBLIC;
create or replace schema METADATACONTROLDB.PUBLIC;
create or replace schema PC_DBT_DB.DBT_SELUMALAI;
create or replace schema PC_DBT_DB.DBT_SELUMALAI_DBT_TEST__AUDIT;
create or replace schema PC_DBT_DB.METADATA;
create or replace schema PC_DBT_DB.PUBLIC;
create or replace schema PC_DBT_DB.UNIT;
create or replace schema TEST.PUBLIC;
create or replace schema TEST.STG;
create or replace masking policy TEST.STG.MOBILE_NUMBER_MASKING_POLICY as (VAL NUMBER(38,0)) 
returns NUMBER(38,0) ->
CASE
  WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN val
  ELSE 'XX-XXXX-XXXX-' || SUBSTR(val, -0)
END
;
create or replace TABLE DBT_DEV.INTEGRATION.CUSTOMER_ORDER_ANALYSIS (
	ID NUMBER(18,0),
	CUSTOMER_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	ORDER_ID NUMBER(38,0),
	ORDER_DATE DATE,
	ORDER_STATUS NUMBER(38,0),
	TOTAL_ORDER_VALUE NUMBER(38,2),
	BOUGHTAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION.CUST_WITH_PROD (
	ID NUMBER(18,0),
	"C.CUSTOMERID+1" NUMBER(38,0),
	CUSTOMERNAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	PRODUCTID NUMBER(38,0),
	PRODUCTNAME VARCHAR(16777216),
	PRODUCTCATEGORY VARCHAR(16777216),
	UNITPRICE NUMBER(10,2),
	QUANTITY NUMBER(38,0),
	LISTPRICE NUMBER(38,0),
	DISCOUNT NUMBER(38,0),
	UPDATEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION.PRODUCTS_NOT_SOLD (
	ID NUMBER(18,0),
	PRODUCT_ID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	PRODUCTIONAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION.SALES_BY_BRAND (
	ID NUMBER(18,0),
	BRAND_ID NUMBER(38,0),
	BRAND_NAME VARCHAR(16777216),
	TOTAL_SALES NUMBER(38,2),
	CREATEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION.SALES_BY_CATEGORY (
	ID NUMBER(18,0),
	CATEGORY_ID NUMBER(38,0),
	CATEGORY_NAME VARCHAR(16777216),
	TOTAL_SALES NUMBER(38,2),
	MARKETEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION.STAFFS_WITH_NO_ORDERS (
	ID NUMBER(18,0),
	STAFF_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	COMMENCEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION.STAFF_PERFORMANCE (
	ID NUMBER(18,0),
	STAFF_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	TOTAL_ORDERS NUMBER(18,0),
	TOTAL_SALES NUMBER(38,2),
	COMMENCEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.INTEGRATION_MARTS.PPF (
	ID NUMBER(18,0),
	PRODUCT_ID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	PRODUCTIONAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_DEV.META.AUDITLOG (
	AUDITLOGID NUMBER(38,0) autoincrement start 1 increment 1 order,
	INVOCATIONID VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	TABLENAME VARCHAR(16777216),
	RESOURCETYPE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERRORLOG VARCHAR(16777216) DEFAULT 'NA',
	MODELCODEVERSION VARCHAR(16777216),
	EXECUTIONSTARTTIME TIMESTAMP_NTZ(9),
	EXECUTIONSENDTIME TIMESTAMP_NTZ(9),
	EXECUTIONTIME FLOAT,
	ROWSAFFECTED NUMBER(38,0)
);
create or replace TABLE DBT_DEV.META.AUDITLOG_TEST (
	AUDITLOGID NUMBER(38,0) autoincrement start 1 increment 1 order,
	INVOCATIONID VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	TESTNAME VARCHAR(16777216),
	RESOURCETYPE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERRORLOG VARCHAR(16777216),
	MODELCODEVERSION VARCHAR(16777216),
	EXECUTIONSTARTTIME TIMESTAMP_NTZ(9),
	EXECUTIONENDTIME TIMESTAMP_NTZ(9),
	EXECUTIONTIME FLOAT,
	ROWSAFFECTED NUMBER(38,0)
);
create or replace TABLE DBT_DEV.META.DBTCONTROL (
	DBTCONTROLID NUMBER(38,0) autoincrement start 1 increment 1 order,
	SCHEMANAME VARCHAR(16777216),
	OBJECTNAME VARCHAR(16777216),
	DBTMATERIALIZATION VARCHAR(16777216),
	UNIQUECOLUMN VARCHAR(16777216),
	SQLQUERY VARCHAR(16777216),
	HWMCOLUMN VARCHAR(16777216),
	ISMODELCREATED VARCHAR(16777216),
	ISMODELUPDATED VARCHAR(16777216) DEFAULT 'NOT UPDATED',
	INSERTUSER VARCHAR(16777216) DEFAULT CURRENT_USER(),
	TARGETMODELDIRECTORY VARCHAR(16777216)
);
create or replace TABLE DBT_DEV.META.DBTSOURCECONTROL (
	SOURCEGENERATIONID NUMBER(38,0) autoincrement start 1 increment 1 order,
	SOURCENAME VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	LAYERREPRESENTATION VARCHAR(16777216),
	INSERTUSER VARCHAR(16777216) DEFAULT CURRENT_USER(),
	INSERTDATE DATE DEFAULT CURRENT_DATE(),
	TARGETSOURCEDIRECTORY VARCHAR(16777216) DEFAULT 'NA'
);
create or replace TABLE DBT_DEV.META.METADATA_SOURCE_TEST (
	"DbtControlId" NUMBER(38,0) autoincrement start 1 increment 1 order,
	"DatabaseName" VARCHAR(16777216),
	"SchemaName" VARCHAR(16777216),
	"TableName" VARCHAR(16777216),
	"UniqueColumn" VARIANT,
	"Notnull" VARIANT,
	"LoadFreshness" VARIANT
);
create or replace TABLE DBT_DEV.PUBLIC.ENTAIN_SIT_DB_DEPLOYMENT_HISTORY (
	SCHEMA_NAME VARCHAR(16777216),
	OBJECT_NAME VARCHAR(16777216),
	VERSIONED_OBJECT_NAME VARCHAR(16777216),
	ARGUMENTS VARCHAR(16777216),
	CREATED TIMESTAMP_LTZ(3),
	LAST_DDL TIMESTAMP_LTZ(3),
	OBJECT_TYPE VARCHAR(16777216)
);
create or replace TABLE DBT_DEV.STG.CUSTOMERS (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIPCODE VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.DW_CUSTOMER (
	CUSTOMERID NUMBER(38,0),
	CUSTOMERNAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE VARCHAR(16777216),
	UPDATEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.DW_PRODUCT (
	PRODUCTID NUMBER(38,0),
	PRODUCTNAME VARCHAR(16777216),
	PRODUCTCATEGORY VARCHAR(16777216),
	UNITPRICE NUMBER(10,2),
	MANUFACTUREDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.DW_SALES (
	PRODUCTID NUMBER(38,0),
	CUSTOMERID NUMBER(38,0),
	STAFFID NUMBER(38,0),
	STOREID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	DISCOUNT NUMBER(38,0),
	LISTPRICE NUMBER(38,0),
	SOLDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.DW_STAFF (
	STAFFID NUMBER(38,0),
	STAFFNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	JOINEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.DW_STORE (
	STOREID NUMBER(38,0),
	STORENAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE NUMBER(38,0),
	OPENEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.EMPLOYEE (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	AGE NUMBER(38,0)
);
create or replace TABLE DBT_DEV.STG.JOB_DETAILS (
	ID NUMBER(38,0),
	DEPARTMENT VARCHAR(16777216),
	SKILLS VARCHAR(16777216)
);
create or replace TABLE DBT_DEV.STG.MOBILE_INFO (
	MOBILE_ID NUMBER(38,0),
	MOBILE_NAME VARCHAR(16777216),
	MOBILE_TYPE VARCHAR(16777216),
	MANUFACTURED_LOCATION VARCHAR(16777216),
	MANUFACTURED_DATE TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.ORDERITEMS (
	ORDERITEMID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNITPRICE NUMBER(38,0),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.ORDERS (
	ORDERID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CUSTOMERID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	STOREID NUMBER(38,0),
	STATUS VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.PERSONAL_DETAILS (
	ROLLNO NUMBER(38,0),
	BLOODGROUP VARCHAR(16777216),
	CITY VARCHAR(16777216),
	MODIFIEDDATE TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.PRODUCTION_BRANDS (
	BRAND_ID NUMBER(38,0),
	BRAND_NAME VARCHAR(16777216),
	CREATEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.PRODUCTION_CATEGORIES (
	CATEGORY_ID NUMBER(38,0),
	CATEGORY_NAME VARCHAR(16777216),
	MARKETEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.PRODUCTION_PRODUCTS (
	PRODUCT_ID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	BRAND_ID NUMBER(38,0),
	CATEGORY_ID NUMBER(38,0),
	MODEL_YEAR NUMBER(38,0),
	LIST_PRICE NUMBER(10,2),
	PRODUCTIONAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.PRODUCTION_STOCKS (
	STORE_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	STOREDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.SALES_CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE NUMBER(38,0),
	BOUGHTAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.SALES_ORDERS (
	ORDER_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	ORDER_STATUS NUMBER(38,0),
	ORDER_DATE DATE,
	REQUIRED_DATE DATE,
	SHIPPED_DATE DATE,
	STORE_ID NUMBER(38,0),
	STAFF_ID NUMBER(38,0),
	ORDEREDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.SALES_ORDER_ITEMS (
	ORDER_ID NUMBER(38,0),
	ITEM_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	LIST_PRICE NUMBER(10,2),
	DISCOUNT NUMBER(2,2),
	TAGGEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.SALES_STAFFS (
	STAFF_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	ACTIVE NUMBER(38,0),
	STORE_ID NUMBER(38,0),
	MANAGER_ID NUMBER(38,0),
	COMMENCEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.SALES_STORES (
	STORE_ID NUMBER(38,0),
	STORE_NAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE NUMBER(38,0),
	STARTEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_DEV.STG.STUDENT_DETAILS (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	AGE NUMBER(38,0),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216)
);
create or replace TABLE DBT_DEV.STG.USER_INFO (
	USER_ID NUMBER(38,0),
	USER_NAME VARCHAR(16777216),
	USER_LOCATION VARCHAR(16777216),
	GENDER VARCHAR(16777216),
	PURCHASE_DATE TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.INTEGRATION.CUSTOMER_ORDER_ANALYSIS (
	ID NUMBER(18,0),
	CUSTOMER_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	ORDER_ID NUMBER(38,0),
	ORDER_DATE DATE,
	ORDER_STATUS NUMBER(38,0),
	TOTAL_ORDER_VALUE NUMBER(38,2),
	BOUGHTAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.INTEGRATION.CUST_WITH_PROD (
	ID NUMBER(18,0),
	CUSTOMERID NUMBER(38,0),
	CUSTOMERNAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	PRODUCTID NUMBER(38,0),
	PRODUCTNAME VARCHAR(16777216),
	PRODUCTCATEGORY VARCHAR(16777216),
	UNITPRICE NUMBER(10,2),
	QUANTITY NUMBER(38,0),
	LISTPRICE NUMBER(38,0),
	DISCOUNT NUMBER(38,0),
	UPDATEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.INTEGRATION.PRODUCTS_NOT_SOLD (
	ID NUMBER(18,0),
	PRODUCT_ID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	PRODUCTIONAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.INTEGRATION.SALES_BY_BRAND (
	ID NUMBER(18,0),
	BRAND_ID NUMBER(38,0),
	BRAND_NAME VARCHAR(16777216),
	TOTAL_SALES NUMBER(38,2),
	CREATEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.INTEGRATION.SALES_BY_CATEGORY (
	ID NUMBER(18,0),
	CATEGORY_ID NUMBER(38,0),
	CATEGORY_NAME VARCHAR(16777216),
	TOTAL_SALES NUMBER(38,2),
	MARKETEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.INTEGRATION.STAFFS_WITH_NO_ORDERS (
	ID NUMBER(18,0),
	STAFF_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	COMMENCEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.INTEGRATION.STAFF_PERFORMANCE (
	ID NUMBER(18,0),
	STAFF_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	TOTAL_ORDERS NUMBER(18,0),
	TOTAL_SALES NUMBER(38,2),
	COMMENCEDAT TIMESTAMP_NTZ(9),
	INVOCATION_ID VARCHAR(36)
);
create or replace TABLE DBT_SIT.META.AUDITLOG (
	AUDITLOGID NUMBER(38,0) autoincrement start 1 increment 1 order,
	INVOCATIONID VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	TABLENAME VARCHAR(16777216),
	RESOURCETYPE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERRORLOG VARCHAR(16777216) DEFAULT 'NA',
	MODELCODEVERSION VARCHAR(16777216),
	EXECUTIONSTARTTIME TIMESTAMP_NTZ(9),
	EXECUTIONSENDTIME TIMESTAMP_NTZ(9),
	EXECUTIONTIME FLOAT,
	ROWSAFFECTED NUMBER(38,0)
);
create or replace TABLE DBT_SIT.STG.CUSTOMERS (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIPCODE VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.DW_CUSTOMER (
	CUSTOMERID NUMBER(38,0),
	CUSTOMERNAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE VARCHAR(16777216),
	UPDATEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.DW_PRODUCT (
	PRODUCTID NUMBER(38,0),
	PRODUCTNAME VARCHAR(16777216),
	PRODUCTCATEGORY VARCHAR(16777216),
	UNITPRICE NUMBER(10,2),
	MANUFACTUREDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.DW_SALES (
	PRODUCTID NUMBER(38,0),
	CUSTOMERID NUMBER(38,0),
	STAFFID NUMBER(38,0),
	STOREID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	DISCOUNT NUMBER(38,0),
	LISTPRICE NUMBER(38,0),
	SOLDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.DW_STAFF (
	STAFFID NUMBER(38,0),
	STAFFNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	JOINEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.DW_STORE (
	STOREID NUMBER(38,0),
	STORENAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE NUMBER(38,0),
	OPENEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.EMPLOYEE (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	AGE NUMBER(38,0)
);
create or replace TABLE DBT_SIT.STG.JOB_DETAILS (
	ID NUMBER(38,0),
	DEPARTMENT VARCHAR(16777216),
	SKILLS VARCHAR(16777216)
);
create or replace TABLE DBT_SIT.STG.MOBILE_INFO (
	MOBILE_ID NUMBER(38,0),
	MOBILE_NAME VARCHAR(16777216),
	MOBILE_TYPE VARCHAR(16777216),
	MANUFACTURED_LOCATION VARCHAR(16777216),
	MANUFACTURED_DATE TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.ORDERITEMS (
	ORDERITEMID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNITPRICE NUMBER(38,0),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.ORDERS (
	ORDERID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CUSTOMERID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	STOREID NUMBER(38,0),
	STATUS VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.PERSONAL_DETAILS (
	ROLLNO NUMBER(38,0),
	BLOODGROUP VARCHAR(16777216),
	CITY VARCHAR(16777216),
	MODIFIEDDATE TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.PRODUCTION_BRANDS (
	BRAND_ID NUMBER(38,0),
	BRAND_NAME VARCHAR(16777216),
	CREATEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.PRODUCTION_CATEGORIES (
	CATEGORY_ID NUMBER(38,0),
	CATEGORY_NAME VARCHAR(16777216),
	MARKETEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.PRODUCTION_PRODUCTS (
	PRODUCT_ID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	BRAND_ID NUMBER(38,0),
	CATEGORY_ID NUMBER(38,0),
	MODEL_YEAR NUMBER(38,0),
	LIST_PRICE NUMBER(10,2),
	PRODUCTIONAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.PRODUCTION_STOCKS (
	STORE_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	STOREDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.SALES_CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE NUMBER(38,0),
	BOUGHTAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.SALES_ORDERS (
	ORDER_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	ORDER_STATUS NUMBER(38,0),
	ORDER_DATE DATE,
	REQUIRED_DATE DATE,
	SHIPPED_DATE DATE,
	STORE_ID NUMBER(38,0),
	STAFF_ID NUMBER(38,0),
	ORDEREDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.SALES_ORDER_ITEMS (
	ORDER_ID NUMBER(38,0),
	ITEM_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	LIST_PRICE NUMBER(10,2),
	DISCOUNT NUMBER(2,2),
	TAGGEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.SALES_STAFFS (
	STAFF_ID NUMBER(38,0),
	FIRST_NAME VARCHAR(16777216),
	LAST_NAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	ACTIVE NUMBER(38,0),
	STORE_ID NUMBER(38,0),
	MANAGER_ID NUMBER(38,0),
	COMMENCEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.SALES_STORES (
	STORE_ID NUMBER(38,0),
	STORE_NAME VARCHAR(16777216),
	PHONE VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	STREET VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIP_CODE NUMBER(38,0),
	STARTEDAT TIMESTAMP_NTZ(9)
);
create or replace TABLE DBT_SIT.STG.STUDENT_DETAILS (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	AGE NUMBER(38,0),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216)
);
create or replace TABLE DBT_SIT.STG.USER_INFO (
	USER_ID NUMBER(38,0),
	USER_NAME VARCHAR(16777216),
	USER_LOCATION VARCHAR(16777216),
	GENDER VARCHAR(16777216),
	PURCHASE_DATE TIMESTAMP_NTZ(9)
);
create or replace TABLE ENTAINDEV.DBT_SCH.CUSTOMERS (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIPCODE VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE ENTAINDEV.DBT_SCH.EMPLOYEE (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	AGE NUMBER(38,0)
);
create or replace TABLE ENTAINDEV.DBT_SCH.ORDERITEMS (
	ORDERITEMID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNITPRICE NUMBER(38,0),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE ENTAINDEV.DBT_SCH.ORDERS (
	ORDERID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CUSTOMERID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	STOREID NUMBER(38,0),
	STATUS VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
create or replace TABLE ENTAINDEV.DBT_SCH.PERSONAL_DETAILS (
	ROLLNO NUMBER(38,0),
	BLOODGROUP VARCHAR(16777216),
	CITY VARCHAR(16777216)
);
create or replace TABLE ENTAINDEV.DBT_SCH.SALES (
	ID NUMBER(38,0),
	SALES_AMT NUMBER(38,0)
);
create or replace TABLE ENTAINDEV.DBT_SCH.TABLE_FROM_TEMP_RELATION_FOR_DELETE_TARGET_RELATION (
	ORDERID NUMBER(38,0)
);
create or replace TABLE PC_DBT_DB.METADATA.AUDITLOG (
	AUDITLOGID NUMBER(38,0) autoincrement start 1 increment 1 order,
	INVOCATIONID VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	TABLENAME VARCHAR(16777216),
	RESOURCETYPE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERRORLOG VARCHAR(16777216) DEFAULT 'NA',
	MODELCODEVERSION VARCHAR(16777216),
	EXECUTIONSTARTTIME TIMESTAMP_NTZ(9),
	EXECUTIONSENDTIME TIMESTAMP_NTZ(9),
	EXECUTIONTIME FLOAT,
	ROWSAFFECTED NUMBER(38,0)
);
create or replace TABLE PC_DBT_DB.METADATA.AUDITLOG_TEST (
	AUDITLOGID NUMBER(38,0) autoincrement start 1 increment 1 order,
	INVOCATIONID VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	TESTNAME VARCHAR(16777216),
	RESOURCETYPE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERRORLOG VARCHAR(16777216),
	MODELCODEVERSION VARCHAR(16777216),
	EXECUTIONSTARTTIME TIMESTAMP_NTZ(9),
	EXECUTIONENDTIME TIMESTAMP_NTZ(9),
	EXECUTIONTIME FLOAT,
	ROWSAFFECTED NUMBER(38,0)
);
create or replace TABLE PC_DBT_DB.METADATA.DBTCONTROL (
	DBTCONTROLID NUMBER(38,0) autoincrement start 1 increment 1 order,
	SCHEMANAME VARCHAR(16777216),
	OBJECTNAME VARCHAR(16777216),
	DBTMATERIALIZATION VARCHAR(16777216),
	UNIQUECOLUMN VARCHAR(16777216),
	SQLQUERY VARCHAR(16777216),
	HWMCOLUMN VARCHAR(16777216),
	ISMODELCREATED VARCHAR(16777216),
	ISMODELUPDATED VARCHAR(16777216) DEFAULT 'NOT UPDATED',
	INSERTUSER VARCHAR(16777216) DEFAULT CURRENT_USER()
);
create or replace TABLE PC_DBT_DB.METADATA.DBTSOURCECONTROL (
	SOURCEGENERATIONID NUMBER(38,0) autoincrement start 1 increment 1 order,
	SOURCENAME VARCHAR(16777216),
	DATABASENAME VARCHAR(16777216),
	SCHEMANAME VARCHAR(16777216),
	LAYERREPRESENTATION VARCHAR(16777216),
	INSERTUSER VARCHAR(16777216) DEFAULT CURRENT_USER(),
	INSERTDATE DATE DEFAULT CURRENT_DATE()
);
create or replace TABLE PC_DBT_DB.METADATA.METADATACONTROL (
	"DbtControlId" NUMBER(38,0) autoincrement start 1 increment 1 order,
	"SchemaName" VARCHAR(16777216),
	"ObjectName" VARCHAR(16777216),
	"ObjectType" VARCHAR(16777216),
	"UniqueColumn" ARRAY,
	"SQLQuery" VARCHAR(16777216),
	"HWMColumn" VARCHAR(16777216),
	"IsModelCreated" VARCHAR(16777216),
	"InsertUser" VARCHAR(16777216) DEFAULT CURRENT_USER(),
	"CreatedDateTime" TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace TABLE PC_DBT_DB.METADATA.METADATA_SOURCE_TEST (
	"DbtControlId" NUMBER(38,0) autoincrement start 1 increment 1 order,
	"DatabaseName" VARCHAR(16777216),
	"SchemaName" VARCHAR(16777216),
	"TableName" VARCHAR(16777216),
	"UniqueColumn" VARIANT,
	"Notnull" VARIANT,
	"LoadFreshness" VARIANT
);
create or replace TABLE PC_DBT_DB.METADATA.METADATA_TEST (
	"DbtControlId" NUMBER(38,0) autoincrement start 1 increment 1 order,
	"ObjectName" VARCHAR(16777216),
	"Test_case" VARIANT
);
create or replace TABLE PC_DBT_DB.METADATA.METARESCUR (
	"DbtControlId" NUMBER(38,0) autoincrement start 1 increment 1 order,
	"SchemaName" VARCHAR(16777216),
	"ModelName" VARCHAR(16777216),
	"SQLQuery" VARCHAR(16777216)
);
create or replace TABLE PC_DBT_DB.METADATA.UNIT_TEST_RESULTS (
	DBTCONTROLID NUMBER(38,0) autoincrement start 1 increment 1 order,
	INNVOCATION_ID VARCHAR(16777216),
	UNIQUE_ID VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	EXECUTION_TIME FLOAT,
	MESSAGE VARCHAR(16777216),
	INSERTUSER VARCHAR(16777216) DEFAULT CURRENT_USER()
);
create or replace TABLE PC_DBT_DB.PUBLIC.TIME_INT (
	ID NUMBER(38,0) autoincrement start 1 increment 1 order,
	CREATETSP TIMESTAMP_NTZ(9)
);
create or replace TABLE PC_DBT_DB.UNIT.U_CUSTOMER (
	CUSTOMERID NUMBER(38,0) autoincrement start 1 increment 1 order,
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAILID VARCHAR(16777216),
	EMAILDOMAIN VARCHAR(16777216)
);
create or replace TABLE PC_DBT_DB.UNIT.U_MAILDOMAIN (
	DOMAINID NUMBER(38,0) autoincrement start 1 increment 1 order,
	EMAILDOMAIN VARCHAR(16777216)
);
create or replace TABLE TEST.PUBLIC.CONDITION_TRIGGER (
	A NUMBER(38,0)
);
create or replace TABLE TEST.PUBLIC.MAIN_FRAME (
	TRX_ID NUMBER(38,0),
	PROPERTY_ID NUMBER(38,0),
	STATUS VARCHAR(16777216),
	RUN_TIME VARCHAR(16777216)
);
create or replace TABLE TEST.PUBLIC.PROPERTY_LOG (
	PROPERTY_ID NUMBER(38,0),
	PROPERTY_NAME VARCHAR(16777216)
);
create or replace TABLE TEST.PUBLIC.TRIGGER_TIME_SCHEDULE (
	TIME_SCHEDULE VARCHAR(16777216)
);
create or replace TABLE TEST.STG.TEST (
	ID NUMBER(38,0),
	NAME VARCHAR(100),
	MOBILE NUMBER(38,0) WITH MASKING POLICY TEST.STG.MOBILE_NUMBER_MASKING_POLICY
);




create or replace TRANSIENT TABLE DBT_DEV.DBO.CUSTOMER_REVENUE (
	CUSTOMERID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	CUSTOMERNAME VARCHAR(16777216),
	REVENUE NUMBER(38,0),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DBT_INVOCATIONID VARCHAR(36)
);
create or replace TRANSIENT TABLE DBT_DEV.DBO.MY_FIRST_DBT_MODEL (
	ID NUMBER(1,0)
);
create or replace TRANSIENT TABLE DBT_DEV.DBO.PERSONAL_DETAILS (
	ROLLNO NUMBER(38,0),
	NAME VARCHAR(16777216),
	BLOODGROUP VARCHAR(16777216),
	CITY VARCHAR(16777216),
	MODIFIEDDATE TIMESTAMP_NTZ(9),
	DBT_INVOCATIONID VARCHAR(36)
);



























CREATE OR REPLACE PROCEDURE DBT_DEV.META.USP_GENERATE_DBANDSCHEMACREATIONSTMT("DATABASENAME" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '  
  
 
-- ===================================================================================================================================================
-- PROCEDURE NAME          :   USP_GENERATE_DBANDSCHEMACREATIONSTMT
-- SCHEMA NAME             :   META
-- AUTHOR                  :   ANAND PANDIAN
-- CREATED DATE            :   17/11/2023
-- PURPOSE                 :   STORED PROCEDURE TO GENERATING CREATE STATEMENT FOR SCHEMA AND DATABASE WHICH ARE PRESENT IN THE
--                             DEVELOPMENT ENVIRONMENT FOR SIT DEPLOYMENT.
-- RETURN TYPE             :   VARCHAR
-- PRE-REQUISITES          :   1.  META SCHEMA SHOULD EXIST IN METACONTROLDB
-- PROCEDURE CALL EXAMPLE  :   CALL META.USP_GENERATE_DBANDSCHEMACREATIONSTMT(''INTEGRATION'');
-- VALUE RETURNED EXAMPLE  :   ''Success'' ON SUCCESS 
--===================================================================================================================================================
-- ===================================================================================================================================================
-- CHANGE HISTORY
-- DATE         USER                    VERSION     CHANGE
-- 17/11/2023   Anand Pandian           V0.1        Initial Creation
--===================================================================================================================================================
DECLARE SCHEMACREATESTMT   VARCHAR;
        SCHEMASET          RESULTSET;
        RES                VARCHAR;
 
BEGIN
 
SCHEMASET := (SELECT SCHEMA_NAME 
              FROM INFORMATION_SCHEMA.SCHEMATA 
              WHERE SCHEMA_NAME LIKE ''STG%''
             );
 
RES := ''CREATE DATABASE IF NOT EXISTS '' || :DATABASENAME ||'';'';
 
SCHEMACREATESTMT := ''CREATE SCHEMA IF NOT EXISTS '' || :DATABASENAME ||''.'';
 
FOR row_variable in SCHEMASET DO
 
    RES := RES || CHAR(10) || :SCHEMACREATESTMT || row_variable.SCHEMA_NAME || '';'';
 
END FOR;
 
RETURN RES;
 
END
 
';



CREATE OR REPLACE FILE FORMAT DBT_DEV.PUBLIC.DDLOBJECT_FILEFORMAT
	RECORD_DELIMITER = 'NONE'
	FIELD_DELIMITER = 'NONE'
	FILE_EXTENSION = 'SQL'
	SKIP_HEADER = 1
	COMPRESSION = NONE
;
CREATE OR REPLACE FUNCTION DBT_DEV.PUBLIC.SOURCE_REFRENCE_GENERATOR_V_2("SQL" VARCHAR(16777216), "LIST" ARRAY)
RETURNS VARCHAR(16777216)
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
HANDLER = 'transform_query'
AS '

import re

def transform_query(sql,list):
    # Regular expression pattern to match table references
    table_from_sche_table_pattern = r''(from|join)\\s+(\\w+)\\.(\\w+)[\\s+]*''
    table_from_database_schema_table_pattern = r''(from|join)\\s+(\\w+)\\.(\\w+)\\.(\\w+)[\\s+]*''
    table_from_reference_model =r''(from|join)\\s+(\\w+)[\\s+)]''
    def schema_table(match):
        if match.group(1):
            type_join = match.group(1)
            schema_name =  match.group(2)
            table_name = match.group(3)
            patter_compin =f"{{source(''{schema_name}'',''{table_name.upper()}'')}}"
            patter_compin_2=f''{{{patter_compin}}} ''
            if type_join in [''from'',''FROM'']:
                patter_compin_3=f''from {patter_compin_2} ''
            else:
                patter_compin_3=f''join {patter_compin_2} ''
            return patter_compin_3
    def database_schema_table(match):
        if match.group(1):
            type_join = match.group(1)
            database_name =  match.group(2)
            print(database_name)
            schema_name =  match.group(3)
            table_name = match.group(4)
            patter_compin =f"{{source(''{schema_name}'',''{table_name.upper()}'')}}"
            patter_compin_2=f''{{{patter_compin}}} ''
            if type_join in [''from'',''FROM'']:
                patter_compin_3=f''from {patter_compin_2} ''
            else:
                patter_compin_3=f''join {patter_compin_2} ''
            return patter_compin_3
    def single_name(match):
        if match.group(1):
            type_join = match.group(1)
            model_name =  match.group(2)
            if model_name in list:
                print(model_name)
                patter_compin =f"{{ref(''{model_name}'')}}"
                patter_compin_2=f''{{{patter_compin}}}''
                if type_join in [''from'',''FROM'']:
                    patter_compin_3=f''from {patter_compin_2} ''
                else:
                    patter_compin_3=f''join {patter_compin_2} ''
                return patter_compin_3
            else:
                patter_compin =f"{model_name}"
               
                if type_join in [''from'',''FROM'']:
                    patter_compin_3=f''from {patter_compin} ''
                else:
                    patter_compin_3=f''join {patter_compin} ''
                return patter_compin_3
                
    # transformed_sql = re.sub(table_from_sche_table_pattern, schema_table, sql, flags=re.IGNORECASE)
    
    source__database_transform = re.sub(table_from_database_schema_table_pattern, database_schema_table,  sql , flags=re.IGNORECASE)
    source_transform = re.sub(table_from_sche_table_pattern, schema_table, source__database_transform, flags=re.IGNORECASE)
    reference_transform = re.sub(table_from_reference_model, single_name,  source_transform , flags=re.IGNORECASE)
    if reference_transform.find("with ") == -1 and reference_transform.find("WITH ")== -1:
        result_string = reference_transform.replace("from", ",''{{invocation_id}}'' as DBT_InvocationId from ")
    else:

        x=reference_transform
        
        old_substring = "from"
    
        new_substring = ",''{{invocation_id}}'' as DBT_InvocationId from "
        
        x_reversed = x[::-1]
        
        old_substring_reversed = old_substring[::-1]
        new_substring_reversed = new_substring[::-1]
        

        result_string_reversed = x_reversed.replace(
                            old_substring_reversed,
                            new_substring_reversed,
                            1)
        

        result_string = result_string_reversed[::-1]
        
    return result_string
 
';
CREATE OR REPLACE PROCEDURE DBT_DEV.PUBLIC.USP_GENERATEINSERTSTMT("DATABASENAME" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '  


-- ===================================================================================================================================================
-- AUTHOR                  :   ANAND PANDIAN
-- CREATED DATE            :   01/11/2023
-- PROCEDURE NAME          :   USP_GENERATEINSERTSTMT
-- SCHEMA NAME             :   META
-- PURPOSE                 :   STORED PROCEDURE TO GENERATING INSERT STATEMENT FOR SIT DEPLOYMENT.
-- RETURN TYPE             :   VARCHAR
-- PROCEDURE CALL EXAMPLE  :   CALL USP_GENERATEINSERTSTMT(''METACONTROLDB'');
-- VALUE RETURNED EXAMPLE  :   ''Success'' ON SUCCESS 
--===================================================================================================================================================
-- ===================================================================================================================================================
-- CHANGE HISTORY
-- DATE         USER                    VERSION     CHANGE
-- 01/11/2023   Anand Pandian           V0.1        Initial Creation
--===================================================================================================================================================
DECLARE
    METADATASCHEMANAME    VARCHAR;
    METADATATABLENAME     VARCHAR;
    QUALIFIED_TABLENAME   VARCHAR;
    METADATA_DATASET      RESULTSET;
	VALUES_DATASET        RESULTSET;
    INDTABLE_INSERT_STMT  VARCHAR;
    INSERT_STMT           VARCHAR;
	INSERT_QUERY          VARCHAR;
    VALUES_LIST           VARCHAR;
	COLUMN_LIST           VARCHAR;
	FULL_QUERY            VARCHAR;
	EXEC_QUERY            VARCHAR;
    
BEGIN
    METADATA_DATASET := (SELECT TABLE_SCHEMA AS METASCHEMA,
                                TABLE_NAME AS METATABLE
                         FROM INFORMATION_SCHEMA.TABLES
                         WHERE TABLE_SCHEMA = ''META''
                             AND TABLE_TYPE = ''BASE TABLE''
                        );

    INSERT_STMT := '''';
    
    FOR row_variable IN METADATA_DATASET DO

    METADATASCHEMANAME := row_variable.METASCHEMA;
    METADATATABLENAME  := row_variable.METATABLE;

    QUALIFIED_TABLENAME := :DATABASENAME || ''.'' || :METADATASCHEMANAME || ''.'' || :METADATATABLENAME;

    
    	INSERT_QUERY := ''TRUNCATE TABLE '' || :QUALIFIED_TABLENAME || '';'' ||CHAR(10)||
                        ''INSERT INTO '' || :QUALIFIED_TABLENAME || ''('' ||
                           (SELECT LISTAGG (COLUMN_NAME,'', '')
                            WITHIN GROUP(ORDER BY ORDINAL_POSITION)
                            FROM INFORMATION_SCHEMA."COLUMNS" 
                            WHERE TABLE_SCHEMA = :METADATASCHEMANAME 
                                AND TABLE_NAME = :METADATATABLENAME) ||
                            '')'' || CHAR(10) || ''VALUES'' || CHAR(10);
                        
    	SELECT  LISTAGG(CASE WHEN DATA_TYPE NOT IN (''NUMBER'',''FLOAT'') 
    						     THEN ''REPLACE(IFNULL('' || COLUMN_NAME || '', ''''''''),'''''''''''''''','''''''''''''''''''''''')''
                             WHEN DATA_TYPE LIKE (''TIMESTAMP_%'')
                                 THEN ''IFNULL('' || COLUMN_NAME || '', ''''9999-12-31 00:00:00.000'''')''
    					     ELSE ''IFNULL('' || COLUMN_NAME || '', 0)''
    				    END
    				    ,'','') WITHIN GROUP(ORDER BY ORDINAL_POSITION)
    		INTO :COLUMN_LIST
    	FROM INFORMATION_SCHEMA."COLUMNS"
    	WHERE TABLE_SCHEMA || ''.'' || TABLE_NAME = :METADATASCHEMANAME || ''.'' || :METADATATABLENAME;
    
    	EXEC_QUERY := ''SELECT ''''('''''''''''' || CONCAT_WS('''''''''''','''''''''''','' || :COLUMN_LIST || '') || ''''''''''''),'''' AS VALUE FROM ''  ||
                       :METADATASCHEMANAME || ''.'' || :METADATATABLENAME || '';'';
    	
    	VALUES_DATASET := (EXECUTE IMMEDIATE :EXEC_QUERY);
    
        VALUES_LIST := '''';
    
        FOR row_variable IN VALUES_DATASET DO
    
            VALUES_LIST := VALUES_LIST || row_variable.VALUE || CHAR(10);
            
        END FOR;
    
        INSERT_STMT := INSERT_STMT || INSERT_QUERY || SUBSTRING(VALUES_LIST,1,LENGTH(VALUES_LIST)-2) || '';'' || CHAR(10) || '' '' ||CHAR(10); 
        
    END FOR;

 RETURN INSERT_STMT;
    
END

';
CREATE OR REPLACE PROCEDURE DBT_DEV.PUBLIC.USP_GENERATE_DDL_SCRIPTS("P_FILEPATH" VARCHAR(16777216), "P_DBNAME" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE 
    QUERY VARCHAR;
    SCHEMA_NAMES VARCHAR;
    SCRIPT VARCHAR;
    MASTER_QUERY VARCHAR;
    QUERYCOPY VARCHAR;
    RES RESULTSET;

    MASTER_PATH VARCHAR;
    INSERT_STMT VARCHAR;
BEGIN
    MASTER_PATH := P_FILEPATH || ''/MASTER/'';
    CREATE OR REPLACE TEMPORARY TABLE SCHEMA_TABLE(SCHEMA_NAME,DBNAME)
    AS
    SELECT SCHEMA_NAME,CATALOG_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE                 
    SCHEMA_NAME!=''PUBLIC'' AND SCHEMA_NAME!=''INFORMATION_SCHEMA'';

    CREATE OR REPLACE TEMPORARY TABLE OBJECT_TABLE(SCHEMA_NAME,OBJECT_TYPE)
    AS
    SELECT SPLIT_PART(METADATA$FILENAME,''/'',2) AS SCHEMANAME,SPLIT_PART(METADATA$FILENAME,''/'',3) AS OBJECT_TYPE FROM @PUBLIC.DDL_OBJECT_STAGE 
    WHERE METADATA$FILENAME LIKE  ''RESULT/%'' GROUP BY SCHEMANAME,OBJECT_TYPE;

    CREATE OR REPLACE TEMPORARY TABLE GETDDL_SCRIPTS(SCHEMA_NAME VARCHAR,SCRIPT VARCHAR);

    LET SCHEMA_CUR CURSOR FOR SELECT SCHEMA_NAME,DBNAME FROM SCHEMA_TABLE;
    LET OBJECT_CUR CURSOR FOR SELECT SCHEMA_NAME,OBJECT_TYPE FROM OBJECT_TABLE WHERE SCHEMA_NAME=?;
    FOR outer_variable IN SCHEMA_CUR DO
    INSERT_STMT := ''INSERT INTO GETDDL_SCRIPTS(SCHEMA_NAME,SCRIPT)
                 SELECT ''''''|| outer_variable.SCHEMA_NAME||'''''','''''';
    OPEN OBJECT_CUR USING(outer_variable.SCHEMA_NAME);
    FOR inner_variable IN OBJECT_CUR DO
    INSERT_STMT := INSERT_STMT || ''get@'' || outer_variable.DBNAME || ''.PUBLIC.DDL_OBJECT_STAGE/RESULT/'' || inner_variable.SCHEMA_NAME || ''/'' || 
    inner_variable.OBJECT_TYPE || '' ''''''''file://'' || P_FILEPATH || ''/'' || inner_variable.SCHEMA_NAME || ''/'' ||inner_variable.OBJECT_TYPE || 
    '''''''''';'' || CHAR(10);
    END FOR;
    INSERT_STMT := INSERT_STMT || '''''''';
    CLOSE OBJECT_CUR;
    EXECUTE IMMEDIATE : INSERT_STMT;                 
    END FOR;
    IF(EXISTS(SELECT METADATA$FILENAME FROM @PUBLIC.DDL_OBJECT_STAGE/RESULT/POSTDEPLOYMENT_SCRIPTS)) THEN
    INSERT_STMT := ''INSERT INTO GETDDL_SCRIPTS(SCHEMA_NAME,SCRIPT) VALUES(''''POSTDEPLOYMENT_SCRIPTS'''',''''get @''||P_DBNAME||''.PUBLIC.DDL_OBJECT_STAGE/RESULT/POSTDEPLOYMENT_SCRIPTS ''''''''file://''||P_FILEPATH||''/POSTDEPLOYMENT_SCRIPTS'''''''' '''');'';
    EXECUTE IMMEDIATE : INSERT_STMT;
    ELSE
    INSERT_STMT := ''INSERT INTO GETDDL_SCRIPTS(SCHEMA_NAME,SCRIPT) VALUES(''''POSTDEPLOYMENT_SCRIPTS'''','''''''');'';
    EXECUTE IMMEDIATE : INSERT_STMT;
    END IF;


    RES := (SELECT * FROM GETDDL_SCRIPTS);
    LET OBJ_CUR CURSOR FOR RES; 
        
                FOR ROW_VARIABLE IN OBJ_CUR DO
                
                    SCHEMA_NAMES:= UPPER(ROW_VARIABLE.SCHEMA_NAME);
                    SCRIPT:= UPPER(ROW_VARIABLE.SCRIPT);
                        
                    QUERYCOPY := ''COPY INTO @'' || P_DBNAME ||''.PUBLIC.DDL_OBJECT_STAGE/CALLER/'' || SCHEMA_NAMES || ''.SQL FROM ( SELECT SCRIPT FROM GETDDL_SCRIPTS WHERE SCHEMA_NAME ='''''' || SCHEMA_NAMES || '''''') FILE_FORMAT=(FORMAT_NAME=''''PUBLIC.DDLOBJECT_FILEFORMAT'''') OVERWRITE=TRUE SINGLE=TRUE;
                    '';
                    EXECUTE IMMEDIATE :QUERYCOPY;
                
                END FOR;

    DROP TABLE IF EXISTS MASTER_DDL;
    MASTER_QUERY := ''CREATE TEMPORARY TABLE MASTER_DDL 
    AS SELECT LISTAGG(''''!Source '''' || ? || SCHEMA_NAME || ''''.SQL'''' || CHAR(10)) CALLER FROM ''||''GETDDL_SCRIPTS WHERE SCRIPT!='''''''' ''; 
    EXECUTE IMMEDIATE :MASTER_QUERY USING (MASTER_PATH);

    QUERYCOPY := ''COPY INTO @'' || P_DBNAME ||''.PUBLIC.DDL_OBJECT_STAGE/CALLER/MASTER.SQL FROM (SELECT * FROM MASTER_DDL) FILE_FORMAT=(FORMAT_NAME=''''PUBLIC.DDLOBJECT_FILEFORMAT'''') OVERWRITE=TRUE SINGLE=TRUE;
        '';
    
    EXECUTE IMMEDIATE :QUERYCOPY USING (MASTER_PATH);
RETURN 1;
END';





















































































create or replace TRANSIENT TABLE ENTAINDEV.PROCESSING_SCH.CUSTOMERS_HISTORY (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIPCODE VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DBT_SCD_ID VARCHAR(32),
	DBT_UPDATED_AT TIMESTAMP_NTZ(9),
	DBT_VALID_FROM TIMESTAMP_NTZ(9),
	DBT_VALID_TO TIMESTAMP_NTZ(9)
);
create or replace TRANSIENT TABLE ENTAINDEV.PROCESSING_SCH.CUSTOMERS_HISTORY_CHECK (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	ADDRESS VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	ZIPCODE VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DBT_SCD_ID VARCHAR(32),
	DBT_UPDATED_AT TIMESTAMP_NTZ(9),
	DBT_VALID_FROM TIMESTAMP_NTZ(9),
	DBT_VALID_TO TIMESTAMP_NTZ(9)
);
create or replace TRANSIENT TABLE ENTAINDEV.PROCESSING_SCH.ORDERS_STG (
	ORDERID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(9),
	CUSTOMERID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	STOREID NUMBER(38,0),
	STATUSCD VARCHAR(16777216),
	STATUSDESC VARCHAR(16777216),
	UPDATED_AT TIMESTAMP_NTZ(9),
	DBT_UPDATED_AT TIMESTAMP_LTZ(9)
);










create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.FACT_ORDERS (
	ORDER_KEY NUMBER(38,0),
	ORDER_DATE DATE,
	CUSTOMER_KEY NUMBER(38,0),
	STATUS_CODE VARCHAR(1),
	PRIORITY_CODE VARCHAR(15),
	CLERK_NAME VARCHAR(15),
	SHIP_PRIORITY NUMBER(38,0),
	ORDER_COUNT NUMBER(1,0),
	GROSS_ITEM_SALES_AMOUNT NUMBER(24,2),
	ITEM_DISCOUNT_AMOUNT NUMBER(28,2),
	ITEM_TAX_AMOUNT NUMBER(28,2),
	NET_ITEM_SALES_AMOUNT NUMBER(28,2)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.FCT_ORDERS (
	ORDER_KEY NUMBER(38,0),
	ORDER_DATE DATE,
	CUSTOMER_KEY NUMBER(38,0),
	STATUS_CODE VARCHAR(1),
	PRIORITY_CODE VARCHAR(15),
	CLERK_NAME VARCHAR(15),
	SHIP_PRIORITY NUMBER(38,0),
	ORDER_COUNT NUMBER(1,0),
	GROSS_ITEM_SALES_AMOUNT NUMBER(24,2),
	ITEM_DISCOUNT_AMOUNT NUMBER(28,2),
	ITEM_TAX_AMOUNT NUMBER(28,2),
	NET_ITEM_SALES_AMOUNT NUMBER(28,2)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.INT_ORDER_ITEMS (
	ORDER_ITEM_KEY VARCHAR(32),
	ORDER_KEY NUMBER(38,0),
	CUSTOMER_KEY NUMBER(38,0),
	ORDER_DATE DATE,
	ORDER_STATUS_CODE VARCHAR(1),
	PART_KEY NUMBER(38,0),
	SUPPLIER_KEY NUMBER(38,0),
	RETURN_FLAG VARCHAR(1),
	LINE_NUMBER NUMBER(38,0),
	ORDER_ITEM_STATUS_CODE VARCHAR(1),
	SHIP_DATE DATE,
	COMMIT_DATE DATE,
	RECEIPT_DATE DATE,
	SHIP_MODE VARCHAR(10),
	EXTENDED_PRICE NUMBER(12,2),
	QUANTITY NUMBER(12,2),
	BASE_PRICE NUMBER(16,2),
	DISCOUNT_PERCENTAGE NUMBER(12,2),
	DISCOUNTED_PRICE NUMBER(16,2),
	GROSS_ITEM_SALES_AMOUNT NUMBER(12,2),
	DISCOUNTED_ITEM_SALES_AMOUNT NUMBER(16,2),
	ITEM_DISCOUNT_AMOUNT NUMBER(16,2),
	TAX_RATE NUMBER(12,2),
	ITEM_TAX_AMOUNT NUMBER(16,2),
	NET_ITEM_SALES_AMOUNT NUMBER(16,2)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.MY_FIRST_DBT_MODEL (
	ID NUMBER(1,0)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.ORDER_ITEMS (
	ORDER_ITEM_KEY VARCHAR(32),
	ORDER_KEY NUMBER(38,0),
	CUSTOMER_KEY NUMBER(38,0),
	ORDER_DATE DATE,
	ORDER_STATUS_CODE VARCHAR(1),
	PART_KEY NUMBER(38,0),
	SUPPLIER_KEY NUMBER(38,0),
	RETURN_FLAG VARCHAR(1),
	LINE_NUMBER NUMBER(38,0),
	ORDER_ITEM_STATUS_CODE VARCHAR(1),
	SHIP_DATE DATE,
	COMMIT_DATE DATE,
	RECEIPT_DATE DATE,
	SHIP_MODE VARCHAR(10),
	EXTENDED_PRICE NUMBER(12,2),
	QUANTITY NUMBER(12,2),
	BASE_PRICE NUMBER(16,2),
	DISCOUNT_PERCENTAGE NUMBER(12,2),
	DISCOUNTED_PRICE NUMBER(16,2),
	GROSS_ITEM_SALES_AMOUNT NUMBER(12,2),
	DISCOUNTED_ITEM_SALES_AMOUNT NUMBER(16,2),
	ITEM_DISCOUNT_AMOUNT NUMBER(16,2),
	TAX_RATE NUMBER(12,2),
	ITEM_TAX_AMOUNT NUMBER(16,2),
	NET_ITEM_SALES_AMOUNT NUMBER(16,2)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.TIME_INT (
	ID NUMBER(38,0),
	CREATETSP TIMESTAMP_NTZ(9)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.U_CUSTOMER (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	EMAILID VARCHAR(16777216),
	EMAILDOMAIN VARCHAR(16777216)
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.U_ETL_CUST (
	CUSTOMERID NUMBER(38,0),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	FULLNAME VARCHAR(16777216),
	EMAILID VARCHAR(16777216),
	IS_VALID_EMAIL_ADDRESS BOOLEAN
);
create or replace TRANSIENT TABLE PC_DBT_DB.DBT_SELUMALAI.U_MAILDOMAIN (
	DOMAINID NUMBER(38,0),
	EMAILDOMAIN VARCHAR(16777216)
);




































CREATE OR REPLACE PROCEDURE TEST.PUBLIC.INSERTINTOMYTABLE()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  INSERT INTO tEST.PUBLIC.CONDITION_TRIGGER VALUES (1);
  RETURN ''Rows inserted: '' || SQLROWCOUNT;
END;
';
CREATE OR REPLACE PROCEDURE TEST.PUBLIC.INSERTINTOMYTABLE("INPUT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  INSERT INTO trigger_time_schedule  VALUES (:input);
  RETURN ''Rows inserted: '' || SQLROWCOUNT;
END;
';
CREATE OR REPLACE PROCEDURE TEST.PUBLIC.TIME_SCHEDULE("INPUT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
  INSERT INTO tEST.PUBLIC.trigger_time_schedule VALUES (:input);
  RETURN ''Rows inserted: '' || SQLROWCOUNT;
END;
';




